### ISSUE TITLE
Menu Item als aktiv anzeigen beim Scrollen

### ISSUE THREAD

**Issue by ewangler** [scout-ch/hering#11]
Wenn man direkt auf einen submenu klickt wird der entsprechende Menu punkt fett markiert, wenn man jedoch scrollt bleibt dieser fett obwohl man ev bereits auf einem anderen kapitel ist

**Comment by mario-zelger** [comment]
Umgesetzt per 24e2525606004a4b7cdf8785e0af68d5ef24568d.
