### ISSUE TITLE
Übliche Lagerdaten als Preset anbieten

### ISSUE THREAD

**Issue by carlobeltrame** [scout-ch/hering#12]
Möglicherweise verwandt mit #8 oder #7 oder #6

Ich fände es als Coach sehr praktisch, wenn ich in der Kalenderfunktion nicht das Datum von Pfingsten, Auffahrt, Sommerferien, Herbstferien und Frühlingsferien erst heraussuchen müsste, sondern der digitale Hering das bei der Kalenderfunktion vorschlagen würde.

Für Pfingsten und Auffahrt wäre das sehr einfach. Ich habe mich mal zu Schulferien in der Schweiz schlau gemacht und leider variieren die genauen Eckdaten über Kantone und sogar Gemeinden hinweg relativ stark. Ich habe auch nach bestehenden Open Source Sammlungen von Schulferien in schweizer Gemeinden gesucht, bisher ohne Erfolg. Die Gemeinden bieten meist Webseiten an auf denen die Daten stehen, aber selten wirklich in maschinell lesbarer Form.

Wollte hier trotzdem mal ein Issue zur Ideensammlung eröffnen.

**Comment by carlobeltrame** [comment]
Ich habe einen (kostenpflichtigen) Service mit API gefunden, der die Feriendaten pro Region zu Verfügung stellt: https://www.schulferien.org/schweiz/ferien/2023/

Diese könnte man vielleicht irgendwie clever aggregieren und z.B. Schnellwahl-Buttons "Sommerferien TI", "Sommerferien VS romand" "Sommerferien AI, BL, BS, FR, GE, GL, GR, JU, NE, UR, VD, VS", "Sommerferien AR, BE, FR, LU, NW, OW, SG, SH, SZ, SO, TG", "Sommerferien ZH" und "Sommerferien AG" anzuzeigen.

Oder noch eine Regionsauswahl anzeigen und erst dann die passenden Schnellwahlbuttons für Frühlingsferien, Sommerferien und Herbstferien anzeigen. Pfingsten und Auffahrt sind zum Glück in der ganzen Schweiz am gleichen Datum :sweat_smile:

**Comment by mario-zelger** [comment]
Habe noch das [OpenHolidays API](https://www.openholidaysapi.org/en/) Projekt gefunden. Wenn ich das richtig sehe könnte dies kostenlos genutzt werden.

Ich schaue mir das bei Gelegenheit mal an.

**Comment by mario-zelger** [comment]
Ich habe mal eine Idee implementiert. Im Kalender kannst du nun unter der Auswahl des Lager-Startdatums die Ferien via Modal auflisten.

Was meinst du dazu?

Es ist mit dem OpenHolidays API m. M. n. nicht möglich die Ferienarten schlau zu aggregieren. Je nach Kanton werden für die "gleichen" Ferien unterschiedliche Bezeichnungen verwendet. Es gibt leider keine einheitliche ID o. ä. welche eine Ferienart zusammenfasst.

**Comment by carlobeltrame** [comment]
Wow, sieht genial aus! Merci vielmal!
