### ISSUE TITLE
Textsuche

### ISSUE THREAD

**Issue by Michael-Schaer** [scout-ch/hering#13]
Hallo zusammen,

Kann ich eigentlich den Hering nach Inhalten durchsuchen?

Heute wollte ich z.B. den Teil mit den Infos zum Pfadiprofil suchen (wer die Checkboxes aktivieren kann). Eine Suche nach "Pfadiprofil" wäre doch noch praktisch? :)

**Comment by mario-zelger** [comment]
Textsuche wurde via 4a1cdb79c7c3eefe9a1d1105f5567800882430a0 implementiert. Ich werde dies so bald wie möglich deployen. :)
