### ISSUE TITLE
Kalender als Excel-Datei exportieren können

### ISSUE THREAD

**Issue by carlobeltrame** [scout-ch/hering#17]
Nicht alle Coaches arbeiten mit einem Kalender. Einige möchten vielleicht die Terminliste auch der Lagerleitung weitersenden. Es wäre nützlich wenn der Hering-Kalender auch einen Excel-Export anbieten könnte, ähnlich wie die "Checkliste LKB": 
[303006de-checkliste_kursbetreuung_lkb-20170904-akom.xlsx](https://github.com/scout-ch/hering/files/9573049/303006de-checkliste_kursbetreuung_lkb-20170904-akom.xlsx)

**Comment by mario-zelger** [comment]
Ich schaue mir eine Implementation als CSV-Export an. Die Arbeit mit Excel-Bibliotheken sind meiner Erfahrung nach eher mühsam / aufwändig. CSV wäre zudem Produktunabhängig (MS Office, OpenOffice, Numbers etc.)

**Comment by mario-zelger** [comment]
Eine CSV-Downloadvariante ist nun vorhanden. Ich schaue mir die Excelmöglichkeit trotzdem noch mit [SheetJS](https://docs.sheetjs.com/docs/) an.

**Comment by mario-zelger** [comment]
Excel Export ist nun in der neusten Version verfügbar.
