### ISSUE TITLE
Lizenz

### ISSUE THREAD

**Issue by Michael-Schaer** [scout-ch/hering#18]
Würde es Sinn machen, hier ein License-File hinzuzufügen?
https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/adding-a-license-to-a-repository

Bisher haben wir jeweils GNU General Public License v3.0 verwendet.

**Comment by mario-zelger** [comment]
Ich würde hier AGPLv3 vorschlagen. Damit muss der modifizierte Source Code auch beim Betrieb als Webseite öffentlich gestellt werden.

https://de.wikipedia.org/wiki/GNU_Affero_General_Public_License

> Die GNU Affero General Public License (AGPL) ist eine [Lizenz für freie Software](https://de.wikipedia.org/wiki/Lizenz#Freie_Software_und_Open_Source) mit [Copyleft](https://de.wikipedia.org/wiki/Copyleft), bei der die Nutzer der Software eine Downloadmöglichkeit für den [Quelltext](https://de.wikipedia.org/wiki/Quelltext) selbst dann erhalten müssen, wenn die Software nur auf einem Server als Dienst betrieben, also nicht direkt zum Download angeboten wird.

**Comment by mario-zelger** [comment]
Ich habe die AGPL v3 Lizenz nun hinzugefügt.
