### ISSUE TITLE
eCamp Schnittstelle

### ISSUE THREAD

**Issue by ewangler** [scout-ch/hering#7]
todos und Lagerdaten aus dem ecamp laden

**Comment by mario-zelger** [comment]
Ich schliesse diese Issue da via #12 aus meiner Sicht eine gute Unterstützung für die Auswahl von möglichen Lagerdaten angeboten wird. Zudem bringt eine zusätzliche Schnittstelle wieder einiges an Komplexität mit sich.

Es wurde nicht geprüft, ob die Daten via eCamp v3 überhaupt abgerufen werden könnten.
