### ISSUE TITLE
Kalenderabfrage merken

### ISSUE THREAD

**Issue by ewangler** [scout-ch/hering#8]
Die Kalenderabfrage muss jedesmal neu gemacht werden wenn die Seite verlassen wird. Es wäre schön wenn sich der Hering die Abfrage merkt.

**Comment by mario-zelger** [comment]
Die Formularwerte beim Kalender werden nun via `sessionStorage` gespeichert (f88c591085f6254445f65e4d66704d7dc370cfd9).
